### ISSUE TITLE
Lying Referees

### ISSUE THREAD

**Issue by michielbdejong** [gotchoices/ChipNet#3]
In the [section on lying referees](https://github.com/gotchoices/ChipNet/blob/master/doc/cluster.md#lying-referees) it is stated that:
> This will be discovered during Consensus

However, IIUC the referees only exist for [trusted timestamping](https://en.wikipedia.org/wiki/Trusted_timestamping) of the time at which each node publishes their signature, right? In particular, whether that is before or after the agreed timeout?

So in a case where Alice, Bob and Charlie each sign a Promise but also each act as a referee, if Bob and Charlie later get cold feet and collude against Alice to incorrectly judge that at least one of the promises arrived after the timeout, even though it didn't, then how will this be discovered during Consensus?

**Comment by michielbdejong** [comment]
Bob and Charlie may also collude to play dead, for years, and then when they want to, publish their vote saying the lift was actually signed in time and the lift goes ahead years after it was initiated.

**Comment by n8allan** [comment]
If Bob and Charlie lie to Alice, telling her that they received the fully promised record too late, when in fact they received it in-time, this is fine.  In fact, though I don't recommend the practice, in principle a referee could arbitrary sign a rejection for reasons beyond timestamping.  Alice will see that Bob and Charlie both rejected it, thus indicating a failed transaction to be rolled back. 
 Where this becomes a lying problem, as far as this algorithm is concerned, is where Bob signs one version of the record as successful, and exchanges that with Charlie, but gives Alice a different version in which he rejects it.  Alice may think it's a failure, while Charlie may think it's a success.  That said, when Charlie exchanges updates with Alice, they both will see the contradiction and instantly know that Bob is not to be trusted.  Should Charlie conspire with Bob, exchanging failure records with each other while both handing her successful ones, we have a situation where the damage depends on where the parties sit in the lift chain, but such effects always affect both sides of the transaction.  If Alice is between Bob and Charlie, the lie to Alice may mean that she pays Charlie, but also means that Bob has paid her.  If she's at the payee end, similarly, Bob or Charlie are on the hook as having paid her.  If she's at the payor end, Alice can show that she paid her part, so it's fairly easy to prove upstream who violated their contract.

**Comment by michielbdejong** [comment]
Ah right, got it!
In Interledger things like this would be much more delicate, due to the connector risk.
But the difference is that you commit all-or-nothing anyway, so the worst that could happen is the case you describe and it's not a way to steal money from Alice.

Thanks! I'll close this now
