### ISSUE TITLE
Consider using a standard timestamp protocol for the referee

### ISSUE THREAD

**Issue by michielbdejong** [gotchoices/ChipNet#4]
If what the referees do is basically trusted timestamping, then maybe you could use some off-the-shelf service for it?

See https://en.wikipedia.org/wiki/Trusted_timestamping#Classification

**Comment by n8allan** [comment]
Transactions are associated with a "session code", which is used as a hash salt for the identities of the tallies in the plan.  This code includes an encoded expiration time, so as part of agreeing to participate in the transaction, all parties are agreeing that said expiration is adequately in the future to have time, but not so far, thus providing an outer limit for dangling and storage.  I haven't though of any cases where anything beyond this matters for the purposes of a lift transaction, but I'm open if you can think of one.

**Comment by michielbdejong** [comment]
I don't think you need to look for applications of the specific things, all of that can stay custom. The only thing I was thinking  is (taking a step back) why do you have a referee in the first place. :Leaving explicit rejections out of scope, distinguish the following cases:
Pending) some signatures are missing, but the timeout has not passed yet
Success) all parties have signed with a valid signature, and the timeout has not passed yet
Timeout) the timeout has passed

The contract refers to the public key used by each participant for signing, so any observer who has access to a clock and who has received all messages that were sent can check what the current state is.

The only situation where you need a referee is if messages are delayed, so that at the moment of timeout, some observers see all required signatures but others do not. Then you need a tie-breaker, to prevent a participant from adding their signature after the timeout, which would be illegal, but hard to detect without a referee.

So an easy way to do that is for each participant to take their signature hash, send it to a standard Time Stamping Authority (TSA), get the proof that yes this signature was created before the timeout, and then add that to the thing every observer can check.

So you would adapt your algorithm so that it includes a call to a standard TSA, and no need for a referee beyond that. Would that work?

**Comment by n8allan** [comment]
I agree that using mere TSAs could work for validating that a signature was made "on time", but I don't see how it addresses the problem of proving a negative.  This goes beyond delays.  If I have a record with 2 of 5 signatures, I have no way to know that another (in time) signature isn't somewhere out there.  I have to get enough positive or negative votes in to be sure of the consensus.  At which point, the consensus is what matters, not really the timing.  Correct?

**Comment by n8allan** [comment]
I'll go ahead and close this for now.  It seems that time agreement seems a way to optimize best case scenarios for transactions, but doesn't change the fundamental dynamics in untrusted environments.
